In [238]:
pip install scikit-learn


[notice] A new release of pip available: 22.3.1 -> 25.0.1
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [239]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import sklearn.metrics

In [240]:
data20 = pd.read_csv("Models20-22/2020seasonDataforModels")
data21 = pd.read_csv("Models20-22/2021seasonDataforModels")
data22 = pd.read_csv("Models20-22/2022seasonDataforModels")

In [241]:
data20 = data20.drop(["SEASON", "Unnamed: 0"], axis = 1)
data21 = data21.drop(["SEASON", "Unnamed: 0"], axis = 1)
data22 = data22.drop(["SEASON", "Unnamed: 0"], axis = 1)

In [242]:
data20.describe()

HOME_LAST_3_GAME_AVG_OE  HOME_LAST_3_GAME_AVG_HOME_WIN_PCTG  \
count              1001.000000                         1001.000000   
mean                  0.561569                            0.527536   
std                   0.033990                            0.176031   
min                   0.429059                            0.000000   
25%                   0.541248                            0.400000   
50%                   0.562347                            0.523810   
75%                   0.583145                            0.634343   
max                   0.653327                            1.000000   

       HOME_NUM_REST_DAYS  HOME_LAST_3_GAME_AVG_AWAY_WIN_PCTG  \
count         1001.000000                         1001.000000   
mean             2.036963                            0.474148   
std              0.976541                            0.172570   
min              1.000000                            0.000000   
25%              2.000000                            0.366458   
50%              2.000000                            0.470588   
75%              2.000000                            0.589382   
max              9.000000                            1.000000   

       HOME_LAST_3_GAME_AVG_TOTAL_WIN_PCTG  \
count                          1001.000000   
mean                              0.500176   
std                               0.140097   
min                               0.000000   
25%                               0.410589   
50%                               0.499629   
75%                               0.592765   
max                               1.000000   

       HOME_LAST_3_GAME_AVG_ROLLING_SCORING_MARGIN  \
count                                 1.001000e+03   
mean                                  2.963703e-02   
std                                   8.460042e+00   
min                                  -2.966667e+01   
25%                                  -5.666667e+00   
50%                                   1.480297e-16   
75%                                   5.777778e+00   
max                                   2.577778e+01   

       HOME_LAST_3_GAME_AVG_ROLLING_OE       HOME_W  \
count                      1001.000000  1001.000000   
mean                          0.561610     0.548452   
std                           0.029661     0.497896   
min                           0.463800     0.000000   
25%                           0.539837     0.000000   
50%                           0.562842     1.000000   
75%                           0.582157     1.000000   
max                           0.642333     1.000000   

       HOME_LAST_3_GAME_AVG_FG_PCT  HOME_LAST_3_GAME_AVG_FG3_PCT  ...  \
count                  1001.000000                   1001.000000  ...   
mean                      0.466310                      0.365861  ...   
std                       0.034553                      0.051651  ...   
min                       0.368667                      0.198667  ...   
25%                       0.442000                      0.332667  ...   
50%                       0.466333                      0.366000  ...   
75%                       0.488667                      0.401000  ...   
max                       0.575667                      0.523667  ...   

       AWAY_LAST_3_GAME_AVG_FG_PCT  AWAY_LAST_3_GAME_AVG_FG3_PCT  \
count                  1001.000000                   1001.000000   
mean                      0.467674                      0.366172   
std                       0.033289                      0.048729   
min                       0.367667                      0.193667   
25%                       0.445333                      0.335333   
50%                       0.468667                      0.367000   
75%                       0.491000                      0.400667   
max                       0.569667                      0.518667   

       AWAY_LAST_3_GAME_AVG_FT_PCT  AWAY_LAST_3_GAME_ROLLING_OE  \
count                  1001.000000                  10

In [243]:
x20 = data20.drop(["HOME_W"], axis=1)
y20 = data20["HOME_W"]
x21 = data21.drop(["HOME_W"], axis=1)
y21 = data21["HOME_W"]
x22 = data22.drop(["HOME_W"], axis=1)
y22 = data22["HOME_W"]

In [244]:
x20

HOME_LAST_3_GAME_AVG_OE  HOME_LAST_3_GAME_AVG_HOME_WIN_PCTG  \
0                    0.595663                            0.888889   
1                    0.585673                            1.000000   
2                    0.521170                            0.000000   
3                    0.507100                            0.000000   
4                    0.517306                            1.000000   
...                       ...                                 ...   
996                  0.500530                            0.262185   
997                  0.508553                            0.382574   
998                  0.563866                            0.796078   
999                  0.530507                            0.457143   
1000                 0.533270                            0.407843   

      HOME_NUM_REST_DAYS  HOME_LAST_3_GAME_AVG_AWAY_WIN_PCTG  \
0                    2.0                            1.000000   
1                    2.0                            1.000000   
2                    3.0                            0.000000   
3                    1.0                            1.000000   
4                    3.0                            0.611111   
...                  ...                                 ...   
996                  2.0                            0.336508   
997                  2.0                            0.194444   
998                  2.0                            0.560847   
999                  2.0                            0.314457   
1000                 1.0                            0.532804   

      HOME_LAST_3_GAME_AVG_TOTAL_WIN_PCTG  \
0                                0.916667   
1                                1.000000   
2                                0.000000   
3                                0.555556   
4                                0.722222   
...                                   ...   
996                              0.300041   
997                              0.285753   
998                              0.676215   
999                              0.385767   
1000                             0.471493   

      HOME_LAST_3_GAME_AVG_ROLLING_SCORING_MARGIN  \
0                                       10.944444   
1                                        8.333333   
2                                       -9.166667   
3                                        2.611111   
4                                       -5.833333   
...                                           ...   
996                                    -25.666667   
997                                    -11.222222   
998                                      0.444444   
999                                    -11.888889   
1000                                    -6.777778   

      HOME_LAST_3_GAME_AVG_ROLLING_OE  HOME_LAST_3_GAME_AVG_FG_PCT  \
0                            0.604766                     0.527333   
1                            0.573508                     0.483333   
2                            0.528442                     0.409000   
3                            0.520630                     0.433333   
4                            0.533900                     0.410333   
...                               ...                          ...   
996                          0.504508                     0.428000   
997                          0.528504                     0.444333   
998                          0.555544                     0.457333   
999                          0.520553                     0.448333   
1000                         0.562585                     0.429000   

      HOME_LAST_3_GAME_AVG_FG3_PCT  HOME_LAST_3_GAME_AVG_FT_PCT  ...  \
0                         0.326333                     0.726000  ...   
1                         0.344333                     0.860000  ...   
2                         0.348000                     0.795667  ...   
3                         0.336000                     0.751333  ...   
4                         0.3

In [245]:
scaler = StandardScaler()
x20 = pd.DataFrame(scaler.fit_transform(x20.values), columns=x20.columns, index=x20.index)
x21 = pd.DataFrame(scaler.fit_transform(x21.values), columns=x21.columns, index=x21.index)
x22 = pd.DataFrame(scaler.fit_transform(x22.values), columns=x22.columns, index=x22.index)

In [246]:
x_train20, x_test20, y_train20, y_test20 = train_test_split(x20, y20, test_size=0.2, random_state=55)
x_train21, x_test21, y_train21, y_test21 = train_test_split(x21, y21, test_size=0.2, random_state=55)
x_train22, x_test22, y_train22, y_test22 = train_test_split(x22, y22, test_size=0.2, random_state=55)

In [247]:
y_train20

723    0
583    1
740    1
503    1
897    1
      ..
893    1
968    1
295    1
666    0
461    1
Name: HOME_W, Length: 800, dtype: int64

In [248]:
lr20 = LogisticRegression()
lr21 = LogisticRegression()
lr22 = LogisticRegression()

In [249]:
lr20.fit(x_train20, y_train20)
lr21.fit(x_train21, y_train21)
lr22.fit(x_train22, y_train22)

LogisticRegression()

In [250]:
pred20 = lr20.predict(x_test20)
pred20_proba = lr20.predict_proba(x_test20)
pred21 = lr21.predict(x_test21)
pred21_proba = lr21.predict_proba(x_test21)
pred22 = lr22.predict(x_test22)
pred22_proba = lr22.predict_proba(x_test22)

In [251]:
print(sklearn.metrics.accuracy_score(y_test20, pred20))
print(sklearn.metrics.accuracy_score(y_test21, pred21))
print(sklearn.metrics.accuracy_score(y_test22, pred22))

0.5771144278606966
0.6163793103448276
0.6190476190476191


In [252]:
pred20_proba

array([[0.18856769, 0.81143231],
       [0.48091441, 0.51908559],
       [0.4830296 , 0.5169704 ],
       [0.40784667, 0.59215333],
       [0.44191073, 0.55808927],
       [0.45849777, 0.54150223],
       [0.19312034, 0.80687966],
       [0.58491885, 0.41508115],
       [0.36678366, 0.63321634],
       [0.61049032, 0.38950968],
       [0.27580816, 0.72419184],
       [0.40186938, 0.59813062],
       [0.36032339, 0.63967661],
       [0.369895  , 0.630105  ],
       [0.50639064, 0.49360936],
       [0.43356543, 0.56643457],
       [0.49968506, 0.50031494],
       [0.51051826, 0.48948174],
       [0.64556026, 0.35443974],
       [0.45601739, 0.54398261],
       [0.2874247 , 0.7125753 ],
       [0.50603228, 0.49396772],
       [0.29907662, 0.70092338],
       [0.33642558, 0.66357442],
       [0.67901068, 0.32098932],
       [0.14503109, 0.85496891],
       [0.19360766, 0.80639234],
       [0.62046608, 0.37953392],
       [0.62101933, 0.37898067],
       [0.37146167, 0.62853833],
       [0.

In [253]:
y_test20

460    1
389    1
373    0
896    0
239    1
      ..
571    1
227    0
335    1
319    1
631    0
Name: HOME_W, Length: 201, dtype: int64

In [254]:
confusion_matrix(y_test20, pred20)

array([[43, 48],
       [37, 73]])

In [256]:
confusion_matrix_20 = sklearn.metrics.confusion_matrix(y_test20, pred20)
print("LCM for 20: ")
print(confusion_matrix_20)
accuracy_20 = sklearn.metrics.accuracy_score(y_test20, pred20)
print("Accuracy for 20: ", end="")
print(accuracy_20)
recall_20 = sklearn.metrics.recall_score(y_test20, pred20)
print("Recall for 20: ", end="")
print(recall_20)
specificity_20 = sklearn.metrics.recall_score(y_test20, pred20, pos_label=0)
print("Specificity for 20: ", end="")
print(specificity_20)
precision_20 = sklearn.metrics.precision_score(y_test20, pred20)
print("Precision for 20: ", end="")
print(precision_20)
f1_20 = sklearn.metrics.f1_score(y_test20, pred20)
print("F1 for 20: ", end="")
print(f1_20)

LCM for 20: 
[[43 48]
 [37 73]]
Accuracy for 20: 0.5771144278606966
Recall for 20: 0.6636363636363637
Specificity for 20: 0.4725274725274725
Precision for 20: 0.6033057851239669
F1 for 20: 0.6320346320346321
